FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    curl \
    wget \
    git \
    gpg \
    xz-utils \
    tar \
    systemd-container \
    && rm -rf /var/lib/apt/lists/*

RUN adduser --disabled-password --gecos '' user
RUN su user -c 'gpg --keyserver keyserver.ubuntu.com --recv  534E4209AB49EEE1C19D96162C44695DB9F6043D'

ADD ./looqs-bundle/ /opt/looqs-bundle/
WORKDIR /opt/looqs-bundle
RUN chmod 777 . -R
RUN su user -c ./scripts/1-create.sh
RUN ./scripts/2-create.sh