name: Docker image builder

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check out code
        uses: actions/checkout@v2

      - name: init submodules
        run: git submodule update --init --recursive

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          pull: true
          tags: ghcr.io/alexander-lindner/looqs-bundle-ci/builder:latest
          context: ./
          file: ./Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max