name: systemd image builder

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check out code
        uses: actions/checkout@v2

      - name: init submodules
        run: git submodule update --init --recursive

      - name: add user
        run: sudo adduser --disabled-password --gecos '' user

      - name: add gpg key
        run: sudo su user -c 'gpg --keyserver keyserver.ubuntu.com --recv  534E4209AB49EEE1C19D96162C44695DB9F6043D'

      - name: build
        run: cd looqs-bundle && sudo chmod 777 . -R  && ./build